#!/usr/bin/env python3
from helpers import get_user_timeline
from analyzer import Analyzer
from sys import argv, path
from termcolor import colored
import os

# TODO
if __name__ == "__main__":
    if len(argv) != 2:
        print('Usage:', argv[0], '@screen_name')
        exit(0)
        
    tweets = get_user_timeline(argv[1].lstrip("@"), 50)
    analyzer = Analyzer(os.path.join(path[0], "positive-words.txt"), os.path.join(path[0], "negative-words.txt"))
    
    for tweet in tweets:
        score = analyzer.analyze(tweet)
        
        if score > 0.0:
            print(colored(' ' + str(score) + ' ' + tweet, "green"))
        elif score < 0.0:
            print(colored(str(score) + ' ' + tweet, "red"))
        else:
            print(colored(' ' + str(score) + ' ' + tweet, "yellow"))